name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub (optional, if pushing the image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t shawnleehere/pg-tools:${{ github.sha }} .
      
      # Tag and Push the Docker image (optional)
      - name: Push Docker image
        run: |
          docker tag shawnleehere/pg-tools:${{ github.sha }} shawnleehere/pg-tools:latest
          docker push shawnleehere/pg-tools:${{ github.sha }}
          docker push shawnleehere/pg-tools:latest
